// Verify the standalone guide, including accessible controls and narrow screens.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const {pathToFileURL}=require('node:url');
let browser;
async function main(){
 const file=path.resolve(process.argv[2]||path.join(__dirname,'../docs/pipeline-guide.html'));
 const out=path.resolve(process.argv[3]||path.join(__dirname,'../output/guide-qa'));
 fs.mkdirSync(out,{recursive:true});
 browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(file).href);
 assert.equal(await page.locator('.source-card:visible').count(),7);
 await page.locator('[data-source-filter="student"]').click();
 assert.equal(await page.locator('.source-card:visible').count(),3);
 assert.equal(await page.locator('#source-count').innerText(),'3 source groups');
 await page.locator('[data-source-filter="all"]').click();
 await page.locator('#tab-quality').click();
 assert.equal(await page.locator('#panel-quality').isVisible(),true);
 assert.equal(await page.locator('#panel-process').isVisible(),false);
 await page.locator('#tab-quality').press('ArrowLeft');
 assert.equal(await page.locator('#tab-process').getAttribute('aria-selected'),'true');
 await page.locator('#role-select').selectOption('data');
 assert.match(await page.locator('#course-names').innerText(),/Fundamentals of Data Engineering/);
 await page.locator('#role-select').selectOption('product');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.equal(await page.locator('script[src],link[rel="stylesheet"]').count(),0);
 const missingAnchors=await page.evaluate(()=>[...document.querySelectorAll('a[href^="#"]')].filter(a=>!document.querySelector(a.getAttribute('href'))).map(a=>a.getAttribute('href')));
 assert.deepEqual(missingAnchors,[]);
 for(const section of ['.hero','#sources','#discovery','#resume'])await page.locator(section).screenshot({path:path.join(out,section.replace(/[.#]/g,'')+'-desktop.png')});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.locator('.hero').screenshot({path:path.join(out,'hero-mobile.png')});
 await page.locator('#sources').screenshot({path:path.join(out,'sources-mobile.png')});
 await page.emulateMedia({media:'print'});
 assert.equal(await page.locator('#panel-quality').isVisible(),true);
 assert.equal(await page.locator('#panel-process').isVisible(),true);
 assert.deepEqual(errors,[]);
 await page.emulateMedia({media:'screen'});
 const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});
 const fallback=await nojs.newPage();await fallback.goto(pathToFileURL(file).href);
 assert.equal(await fallback.locator('.source-card:visible').count(),7);
 assert.equal(await fallback.locator('#panel-quality').isVisible(),true);
 assert.equal(await fallback.locator('#panel-process').isVisible(),true);
 await browser.close();console.log('Guide passed: filtering, tabs/keyboard, course selection, anchors, mobile, print, no-JS and no page errors.');
}
main().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
